name: "[Cloud Pública] Criação de repositório"
description: Criação de repositório para deploy na Cloud Pública (AWS)
title: "Criação de repositório para Cloud Pública"
labels: ["repositorio", "cloud-publica"]
assignees: "teste"
body:
  - type: markdown
    attributes:
      value: "Formulário padrão para criação de repositório no GitHub"
  - type: input
    id: acronym
    attributes:
      label: ">>Sigla do produto<<"
      description: Sigla do produto
      placeholder: IU2
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: ">>Nome da aplicação<<"
      description: Nome da aplicação ou serviço
      placeholder: nomedaminhaaplicacao
    validations:
      required: true
  - type: dropdown
    id: privacy
    attributes:
      label: ">>Privacidade<<"
      description: Este repositório deve ser privado ou interno?
      options:
    validations:
      required: true
  - type: dropdown
    id: template
    attributes:
      label: ">>Template<<"
      description: Este repositório é para qual recurso? Obs.(O template itau-up2-template-infra-terraform está disponível na jornada [Cloud Pública] Criação de repositório de infra na tela anterior)
      options:
    validations:
      required: true
  - type: input
    id: conta_aws
    attributes:
      label: ">>Nome Conta AWS<<"
      description: Nome da Conta AWS
      placeholder: nomedaminhaconta
    validations:
      required: true
  - type: dropdown
    id: create_sigla_app
    attributes:
      label: ">>Criar SiglaApp<<"
      description: Gostaria de criar agora a SiglaApp para o repositório?
      options:
    validations:
      required: true
  - type: input
    id: application_service_id
    attributes:
      label: ">>Serviço de Aplicação<<"
      description: Número do serviço de aplicação. (OPCIONAL)
      placeholder: SNSVC0001234
    validations:
      required: false
