blank_issues_enabled: false
issue_templates:
  - name: "AWS ECS"
    description: "Criar um reposit칩rio novo com a estrutura b치sica do Terraform para um AWS ECS"
    labels: ["terraform", "ecs", "infra"]
    file: aws-ecs.yml

  - name: "AWS SQS"
    description: "Criar um reposit칩rio novo com a estrutura b치sica do Terraform para um AWS SQS"
    labels: ["terraform", "sqs", "infra"]
    file: aws-sqs.yml
